
http://localhost:3000/players/

###
GET http://localhost:3000/players/1/


###
http://localhost:3000/matches/1/



###
PUT http://localhost:3000/players/1/
Content-Type:  application/json

{
  "playerName": "manju"
}